"""empty message

Revision ID: 7bc256a11fd8
Revises: d71cbbb1fdca
Create Date: 2020-08-19 22:33:05.068069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bc256a11fd8'
down_revision = 'd71cbbb1fdca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('commpeleted', sa.Boolean(), nullable=True))
    op.execute('UPDATE todos SET commpeleted = False WHERE commpeleted IS NULL;')
    op.alter_column('todos','commpeleted',nullable=False)
    op.alter_column('todos', 'commpeleted', new_column_name='completed')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'completed')
    # ### end Alembic commands ###
